### ISSUE TITLE
Null reference exceptions in cache FS

### ISSUE THREAD

**Issue by stephen-palmer** [Unity-Technologies/unity-cache-server#100]
- `Cannot read property 'clientAddress' of null`
- `UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'autosave' of undefined`

**Comment by mikkelfredborg** [comment]
We're getting the clientAddress null error quite often, it looks like it happens during uploading of assets.

With log level 5:
`
192.168.1.7:53460 connected.
Start transaction for GUID: cd46bf375863e43b6be5160610153219 Hash: 29e0356fbdd8102e9d1b297d48438f6e
Added file to cache: 50584 /usr/local/lib/node_modules/unity-cache-server/.cache_fs/cd/cd46bf375863e43b6be5160610153219-29e0356fbdd8102e9d1b297d48438f6e.info
Added file to cache: 358572 /usr/local/lib/node_modules/unity-cache-server/.cache_fs/cd/cd46bf375863e43b6be5160610153219-29e0356fbdd8102e9d1b297d48438f6e.bin
End transaction for GUID: cd46bf375863e43b6be5160610153219 Hash: 29e0356fbdd8102e9d1b297d48438f6e
Start transaction for GUID: 0c60c8cfe30244476814118a85e5f0cc Hash: b37cee5c9319589fd5a07839eb2ba82e
192.168.1.7:53460 closed connection.
Added file to cache: 633 /usr/local/lib/node_modules/unity-cache-server/.cache_fs/0c/0c60c8cfe30244476814118a85e5f0cc-b37cee5c9319589fd5a07839eb2ba82e.info
Added file to cache: 4244 /usr/local/lib/node_modules/unity-cache-server/.cache_fs/0c/0c60c8cfe30244476814118a85e5f0cc-b37cee5c9319589fd5a07839eb2ba82e.bin
End transaction for GUID: 0c60c8cfe30244476814118a85e5f0cc Hash: b37cee5c9319589fd5a07839eb2ba82e
Cannot read property 'clientAddress' of null
`

**Comment by stephen-palmer** [comment]
> We're getting the clientAddress null error quite often, it looks like it happens during uploading of assets.
> 

Are you running the latest version?

**Comment by mikkelfredborg** [comment]
Yes, cache server 6.3.0 and unity 2018.3.7f1

**Comment by stephen-palmer** [comment]
Thanks. I'll reopen and investigate.

**Comment by psandytang** [comment]
have the same issue as well on 6.3.0. Have to restart the service to accept connections afterward

**Comment by timezombi** [comment]
We are also having this issue in our Cache Server (6.3.0). I receive these messages in the error log.

> [2019-05-02 14:25:58] (node:7739) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'clientAddress' of null
> [2019-05-02 14:25:58]     at CommandProcessor._printReadStats (/usr/local/lib/node_modules/unity-cache-server/lib/server/command_processor.js:209:293)
> [2019-05-02 14:25:58]     at Object.onceWrapper (events.js:277:13)
> [2019-05-02 14:25:58]     at CommandProcessor.emit (events.js:189:13)
> [2019-05-02 14:25:58]     at finishMaybe (_stream_writable.js:641:14)
> [2019-05-02 14:25:58]     at afterWrite (_stream_writable.js:481:3)
> [2019-05-02 14:25:58]     at onwrite (_stream_writable.js:471:7)
> [2019-05-02 14:25:58]     at _writeHandler.then (/usr/local/lib/node_modules/unity-cache-server/lib/server/command_processor.js:106:25)
> [2019-05-02 14:25:58] (node:7739) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
> [2019-05-02 14:25:58] (node:7739) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
> [2019-05-02 15:39:01] (node:7739) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'clientAddress' of null
> [2019-05-02 15:39:01]     at CommandProcessor._printReadStats (/usr/local/lib/node_modules/unity-cache-server/lib/server/command_processor.js:209:293)
> [2019-05-02 15:39:01]     at Object.onceWrapper (events.js:277:13)
> [2019-05-02 15:39:01]     at CommandProcessor.emit (events.js:189:13)
> [2019-05-02 15:39:01]     at finishMaybe (_stream_writable.js:641:14)
> [2019-05-02 15:39:01]     at afterWrite (_stream_writable.js:481:3)
> [2019-05-02 15:39:01]     at onwrite (_stream_writable.js:471:7)
> [2019-05-02 15:39:01]     at _writeHandler.then (/usr/local/lib/node_modules/unity-cache-server/lib/server/command_processor.js:106:25)
> [2019-05-02 15:39:01] (node:7739) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
> [2019-05-02 16:56:15] (node:7739) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'clientAddress' of null
> [2019-05-02 16:56:15]     at CommandProcessor._printReadStats (/usr/local/lib/node_modules/unity-cache-server/lib/server/command_processor.js:209:293)
> [2019-05-02 16:56:15]     at Object.onceWrapper (events.js:277:13)
> [2019-05-02 16:56:15]     at CommandProcessor.emit (events.js:189:13)
> [2019-05-02 16:56:15]     at finishMaybe (_stream_writable.js:641:14)
> [2019-05-02 16:56:15]     at afterWrite (_stream_writable.js:481:3)
> [2019-05-02 16:56:15]     at onwrite (_stream_writable.js:471:7)
> [2019-05-02 16:56:15]     at _writeHandler.then (/usr/local/lib/node_modules/unity-cache-server/lib/server/command_processor.js:106:25)
> [2019-05-02 16:56:15] (node:7739) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)
> [2019-05-02 17:16:22] (node:7739) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'clientAddress' of null
> [2019-05-02 17:16:22]     at CommandProcessor._printReadStats (/usr/local/lib/node_modules/unity-cache-server/lib/server/command_processor.js:209:293)
> [2019-05-02 17:16:22]     at Object.onceWrapper (events.js:277:13)
> [2019-05-02 17:16:22]     at CommandProcessor.emit (events.js:189:13)
> [2019-05-02 17:16:22]     at finishMaybe (_stream_writable.js:641:14)
> [2019-05-02 17:16:22]     at afterWrite (_stream_writable.js:481:3)
> [2019-05-02 17:16:22]     at onwrite (_stream_writable.js:471:7)
> [2019-05-02 17:16:22]     at _writeHandler.then (/usr/local/lib/node_modules/unity-cache-server/lib/server/command_processor.js:106:25)
> [2019-05-02 17:16:22] (node:7739) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 4)

I need to do some more testing when the opportunity presents itself, but we have been having issues with cache server not serving assets stored in the cache. Now that I see some people are also experiencing some issues when they have this error, I will set up some alerts for when these messages appear in the logs.

**Comment by stephen-palmer** [comment]
Fixed in v6.4.0. Beta release is available: https://github.com/Unity-Technologies/unity-cache-server/releases/tag/v6.4.0-beta0
