### ISSUE TITLE
Connections remaining open after client has gone away

### ISSUE THREAD

**Issue by SGDavid** [Unity-Technologies/unity-cache-server#102]
Worker processes seem not to be closing connections after a client goes away; this results in worker processes not being available to active clients. Example:
```
$ netstat -an | egrep "\.8126.*ESTABLISHED"
tcp4       0      0  10.8.210.63.8126       10.8.210.75.53798      ESTABLISHED
tcp4       0      0  10.8.210.63.8126       10.95.109.188.56131    ESTABLISHED
$ ping 10.8.210.75
PING 10.8.210.75 (10.8.210.75): 56 data bytes
Request timeout for icmp_seq 0
Request timeout for icmp_seq 1
^C
--- 10.8.210.75 ping statistics ---
3 packets transmitted, 0 packets received, 100.0% packet loss
$ ping 10.95.109.188
PING 10.95.109.188 (10.95.109.188): 56 data bytes
Request timeout for icmp_seq 0
Request timeout for icmp_seq 1
Request timeout for icmp_seq 2
^C
--- 10.95.109.188 ping statistics ---
4 packets transmitted, 0 packets received, 100.0% packet loss
```

**Comment by stephen-palmer** [comment]
I suspect the editor just didn't "hang up" yet in those cases. Regardless, the workers are not at all limited to a single connection at a time.

I'm not sure what the ping test is proving above? Are you also observing that clients (Editors) can't at some point connect to the cache server at all?

**Comment by stephen-palmer** [comment]
I still don't feel like I have enough information to act on. Let me know if you have any additional info or observations.

**Comment by stephen-palmer** [comment]
closing - please re-open if the problem persists.
