### ISSUE TITLE
Understanding unreliable data from high reliability mode

### ISSUE THREAD

**Issue by Avalix** [Unity-Technologies/unity-cache-server#108]
Hey all,

Are there any docs about how to use the saved out unreliable data via high reliabaility mode for working out issues with the cache server? We seem to have gained quite a few and it would be good to have some steps for analyzing them. 

Also there is a log of .a and .i files with no real pattern to either. What do they represent?

Cheers,
Chris

**Comment by stephen-palmer** [comment]
The unreliable files are organized as such `[GUID]/[version]/[file hash].[type]`.

- GUID - the asset GUID. This can be mapped back to an asset in your project folder using the `AssetDatabase.GUIDToAssetPath()` API
- version - this is also called the "asset hash" and is Unity's way of identifying a unique version of an asset. It's calculated as the MD5 sum of various _inputs_ to the import process.
- file hash - an SHA-256 hash of the contents of the file that was sent to the cache server.
- type - Each asset can have one or more of three types of files: the asset source (*.a), asset meta data (*.i), and resource file (*.r). These are the same files that are stored in the local project Library/metadata folder (though the file extensions differ).

In high reliability mode, the SHA-256 hash of every file sent to the server is calculated and stored in a database. Only after multiple Unity clients send the same exact binary data for each asset GUID+version is the version is cached. When a binary difference is detected, the file is stored in the `.unreliable` folder as described above for later inspection.

Use your favorite binary diff tool to compare files of the same extension within a version folder.

There are a few possible reasons asset imports can be unreliable:
- Differences between Mac/Win Editor imports
- Custom AssetPostprocessor implementations that introduce untracked dependencies that don't get calculated in the asset version hash.
- A bug in an importer.

Sometimes these are harmless. For instance, if you see a difference in the PNG binary data inside a .i file, that's just an Editor preview image.

Let me know what you find out - especially if it looks like an importer bug.

**Comment by stephen-palmer** [comment]
Closing as answered .. please re-open if you want to continue the conversation.
