### ISSUE TITLE
Is it safe for running both cache-server and cache-server-cleanup daemon?

### ISSUE THREAD

**Issue by KichangKim** [Unity-Technologies/unity-cache-server#116]
Hi. I have a quaestion about unity-cache-server-cleanup as damon mode. Is it safe for running both cache-server and cache-server-cleanup daemon in same machine? Should I stop the cache server before running cleanup?

**Comment by SGDavid** [comment]
I have had no problems running nightly cleanup without stopping the cache server. I run five servers in different locations.

**Comment by stephen-palmer** [comment]
Yes, this should generally be safe, unless you are doing something pathological like setting a very short LRU cleanup window (minutes/hours vs. days) where there's a risk of a file being accessed by the client during cleanup.
