### ISSUE TITLE
Be rejected one time will not be cache again

### ISSUE THREAD

**Issue by wlxklyh** [Unity-Technologies/unity-cache-server#118]
Be rejected one time will not be cache again:
First PC1 ip is not in white list and set enable commit to cacheserver 
then resource PC1 request to cache will be rejected  and change the state to reliable and then add PC1 ip to the wihte list.But it can not be cache unless the state is reliablenew.

**Comment by stephen-palmer** [comment]
Thanks for the report - a fix is on the way.

**Comment by stephen-palmer** [comment]
Fixed in v6.4.0. Beta release is available: https://github.com/Unity-Technologies/unity-cache-server/releases/tag/v6.4.0-beta0

**Comment by wlxklyh** [comment]
thx a lot
