### ISSUE TITLE
Multiple Instances of the Same Asset Being requested in a row

### ISSUE THREAD

**Issue by jasongabrielcasale** [Unity-Technologies/unity-cache-server#119]
We are seeing multiple instances of the same GUID assets being requested 4 or 5 times in a row.
This seems weird and these assets are not being submitted back to the cache server.
We checked the GUID on the cache server and those assets are missing.

Here is an example below.

Hashing assets (1 files)... 0.002 seconds
  file read: 0.000 seconds (0.279 MB)
  wait for write: 0.000 seconds (I/O thread blocked by consumer, aka CPU bound)
  wait for read: 0.001 seconds (CPUT thread waiting for I/O thread, aka disk bound)
  hash: 0.000 seconds
Connect to CacheServer unity-cache:8126
Updating Assets/Prototypes/Proto_Missions/Portal_Runner.prefab - GUID: c5b4a74aea204a64499273cf9e1fd2f7...
 done. [Time: 88.991800 ms] 
Script Compilation Pipeline Post Process Assets time: 0.000014s
Assembly Updater Post Process Assets time: 0.000077s
Disconnect from CacheServer
Refreshing native plugins compatible for Editor in 15.07 ms, found 34 plugins.
Preloading 2 native plugins for Editor in 0.27 ms.

Hashing assets (1 files)... 0.002 seconds
  file read: 0.000 seconds (0.279 MB)
  wait for write: 0.000 seconds (I/O thread blocked by consumer, aka CPU bound)
  wait for read: 0.001 seconds (CPUT thread waiting for I/O thread, aka disk bound)
  hash: 0.000 seconds
Connect to CacheServer unity-cache:8126
Updating Assets/Prototypes/Proto_Missions/Portal_Runner.prefab - GUID: c5b4a74aea204a64499273cf9e1fd2f7...
 done. [Time: 123.344600 ms] 
Script Compilation Pipeline Post Process Assets time: 0.000013s
Assembly Updater Post Process Assets time: 0.000057s
Disconnect from CacheServer
Refreshing native plugins compatible for Editor in 15.15 ms, found 34 plugins.
Preloading 2 native plugins for Editor in 0.28 ms.

Hashing assets (1 files)... 0.001 seconds
  file read: 0.000 seconds (0.279 MB)
  wait for write: 0.000 seconds (I/O thread blocked by consumer, aka CPU bound)
  wait for read: 0.001 seconds (CPUT thread waiting for I/O thread, aka disk bound)
  hash: 0.000 seconds
Connect to CacheServer unity-cache:8126
Updating Assets/Prototypes/Proto_Missions/Portal_Runner.prefab - GUID: c5b4a74aea204a64499273cf9e1fd2f7...
 done. [Time: 91.172300 ms] 
Script Compilation Pipeline Post Process Assets time: 0.000012s
Assembly Updater Post Process Assets time: 0.000055s
Disconnect from CacheServer
Refreshing native plugins compatible for Editor in 15.06 ms, found 34 plugins.
Preloading 2 native plugins for Editor in 0.27 ms.

Hashing assets (1 files)... 0.001 seconds
  file read: 0.000 seconds (0.279 MB)
  wait for write: 0.000 seconds (I/O thread blocked by consumer, aka CPU bound)
  wait for read: 0.001 seconds (CPUT thread waiting for I/O thread, aka disk bound)
  hash: 0.000 seconds
Connect to CacheServer unity-cache:8126
Updating Assets/Prototypes/Proto_Missions/Portal_Runner.prefab - GUID: c5b4a74aea204a64499273cf9e1fd2f7...
 done. [Time: 90.860500 ms] 
Script Compilation Pipeline Post Process Assets time: 0.000014s
Assembly Updater Post Process Assets time: 0.000070s
Disconnect from CacheServer
Refreshing native plugins compatible for Editor in 15.10 ms, found 34 plugins.
Preloading 2 native plugins for Editor in 0.27 ms.

Hashing assets (1 files)... 0.001 seconds
  file read: 0.000 seconds (0.279 MB)
  wait for write: 0.000 seconds (I/O thread blocked by consumer, aka CPU bound)
  wait for read: 0.001 seconds (CPUT thread waiting for I/O thread, aka disk bound)
  hash: 0.000 seconds
Connect to CacheServer unity-cache:8126
Updating Assets/Prototypes/Proto_Missions/Portal_Runner.prefab - GUID: c5b4a74aea204a64499273cf9e1fd2f7...
 done. [Time: 91.060400 ms] 
Script Compilation Pipeline Post Process Assets time: 0.000014s
Assembly Updater Post Process Assets time: 0.000057s
Disconnect from CacheServer
Refreshing native plugins compatible for Editor in 15.10 ms, found 34 plugins.
Preloading 2 native plugins for Editor in 0.27 ms.

**Comment by timezombi** [comment]
We are still troubleshooting our weird build issues related to this. This is a symptom from whatever is causing our build times to triple recently. Something possible related is that we are receiving lots of messages claiming that we did not get an expected response from Cache Server.

>  11:27:27 Did not get expected type of response from cache server
> 11:27:33 Did not get expected type of response from cache server
> 11:27:33 Did not get expected type of response from cache server
> 11:27:38 Did not get expected type of response from cache server
> 11:27:38 Did not get expected type of response from cache server
> 11:27:44 Did not get expected type of response from cache server
> 11:27:44 Did not get expected type of response from cache server
> 11:27:49 Did not get expected type of response from cache server
> 11:27:49 Did not get expected type of response from cache server
> 11:27:55 Did not get expected type of response from cache server
> 11:27:55 Did not get expected type of response from cache server
> 11:28:00 Did not get expected type of response from cache server
> 11:28:00 Did not get expected type of response from cache server
> 11:28:05 Did not get expected type of response from cache server
> 11:28:05 Did not get expected type of response from cache server
> 11:28:11 Did not get expected type of response from cache server
> 11:28:11 Did not get expected type of response from cache server
> 11:28:16 Did not get expected type of response from cache server
> 11:28:16 Did not get expected type of response from cache server
> 11:28:22 Did not get expected type of response from cache server

etc, etc.

**Comment by timezombi** [comment]
I see from a previous issue #67, that the "Did not get expected type of response from cache server" could be due to a corrupted cache? I will talk with the team and try to clear the Cache at the next available opportunity.

In the meantime, our build times have dropped back down to a normal time and the multiple asset imports (which admittedly may be unrelated to cache server)  seem to have stopped. We are still actively investigating the issue and waiting for more builds to come out.

**Comment by jasongabrielcasale** [comment]
Brandon,
Confirmed that seems to be true.
Recommendation is to clear the cache and reseed it.
Please take out a service window for this.

Kind Regards with Gratitude,

Jason Casale
Camouflaj
IT

**Comment by timezombi** [comment]
The issue has been resolved. It was due to a rogue Unity Plugin, totally unrelated to Unity Cache Server. The plugin developer submitted a patch and all is good now. This issue can be closed.

**Comment by jasongabrielcasale** [comment]
Closing this is resolved.
A Unity plugin was causing this issue.

**Comment by z5616342** [comment]
@timezombi  Hello, I also encountered this problem, I want to know how you solved this problem, I mean how to find this strange plug-in
