### ISSUE TITLE
Unity 6.4.0 beta: Unity clients unable to connect to Cache Server

### ISSUE THREAD

**Issue by timezombi** [Unity-Technologies/unity-cache-server#126]
At the end of the day, we decided to run the test a little early and briefly deployed the 6.4.0 beta cache server in the studio to see if it would fix the null ref issue (#100) that has been killing our builds.

We deployed this for a total of 30 minutes, during which time we found that many clients were not able to connect to this beta cache server. The Unity Cache Server log showed that the clients were connected but their imports would still hang when attempting to connect to cache server.

After reverting back to 6.3.0, all the clients were able to successfully connect and import again.

When I was looking at the log, I noticed that there was an abnormally high amount of _ECONNRESET_ errors.

[econnreset_errors.log](https://github.com/Unity-Technologies/unity-cache-server/files/3175668/econnreset_errors.log)

I'll set up a proper test environment this week to see if I can reproduce this issue. I'll report back as soon as I find anything promising.

I'm using the existing cache from 6.3.0 with the same configuration files as before. Running in log level 3.

**Comment by stephen-palmer** [comment]
Fixed in 6.4.0-beta1.
