### ISSUE TITLE
Unity 6.4.0 beta: Log is reporting sending more files than requested.

### ISSUE THREAD

**Issue by timezombi** [Unity-Technologies/unity-cache-server#127]
After running Unity Cache Server 6.4.0 beta for about 30 minutes, I noticed something bizarre in the log... there was a line claiming that more files had been sent than requested! I don't recall ever seeing something like this before, so I assume that this is new in the beta.

> [2019-05-13 18:05:21] clientip:63651 connected.
> [2019-05-13 18:05:22] Sent 180 of 174 requested files (181 chunks) totaling 425.59 KB in 1.108 seconds (384.1 KB/sec) to clientip:63651
> [2019-05-13 18:05:22] clientip:63651 closed connection.

**Comment by stephen-palmer** [comment]
Almost certainly something wrong with the refactored download queue code that the test suite isn't catching. This is why we beta! Thanks for testing.

**Comment by stephen-palmer** [comment]
v6.4.0-beta1 published.

**Comment by stephen-palmer** [comment]
Fixed in 6.4.0-beta2.
