### ISSUE TITLE
Put whitelist don't work as inteded

### ISSUE THREAD

**Issue by tkslan** [Unity-Technologies/unity-cache-server#131]
Hi, put whitelist allows other hosts to send files, or maybe there is some miss configuration I have made...(6.4.0).
unity-cache-server[10964]: [Cluster:2] 91.196.10.26:64640 connected. <--- is still able to PUT (transfer to server occurs)
unity-cache-server[10964]: [Cluster:2] PUT whitelist: 84.10.24.251:8126

**Comment by tkslan** [comment]
Just looked at Protocol.md file. Seems to me like this is a feature, there is no message from server that client is banned from putting assets in.

**Comment by stephen-palmer** [comment]
correct, as we didn't want to modify the protocol or the client side (Unity). Debug logging in v6.4.0 will log an additional message that the transaction was invalidated. The data from the client is written to an empty/null stream.

**Comment by tkslan** [comment]
Is there is a option to stop clients from sending data to cache server, our scenario is multiple clients over Internet, and while data is still sending into null there is a delay on importing caused by outgoing traffic rate...

**Comment by stephen-palmer** [comment]
no, unfortunately, the client is not aware of the restriction. This will be improved in Asset Database V2.

you might be able block outbound traffic on the client firewall to port 8126 destinations. Not something I have tested though.
