### ISSUE TITLE
Error: write ECONNABORTED

### ISSUE THREAD

**Issue by mikelortega** [Unity-Technologies/unity-cache-server#132]
I'm using version 6.3.0 on Windows 10 Pro.
Once in a while the Cache Server stops working, the clients show "Connection failed". Then I press enter in the console where I launched the Cache Server, it shows the **Error: write ECONNABORTED**. After pressing enter the clients can connect again and everything works fine for another while.
Does someone know about it?
Is there anything I can do to avoid pressing enter in the console?

**Comment by stephen-palmer** [comment]
I can't imagine why the console is waiting for input and stalling the process - there is certainly no console interaction code written to do so. I can only think of Windows being the culprit. We'll have to do some testing.

**Comment by mikelortega** [comment]
Thank you Stephen. Tell me anything I can do to give you more info about the error.
