### ISSUE TITLE
[Feature Request] Use compression

### ISSUE THREAD

**Issue by vigo2** [Unity-Technologies/unity-cache-server#134]
At least for our rather texture-rich projects, cache contents are compressing pretty well (2-3x) when using LZ4 compression, which would a) help network transfer times in all cases where it mattered in the first place (100M or WLAN*), b) help with OS caching, and c) help keeping cache sizes in check. b) and c) apply to local caching (and possibly the Library/metadata folder) as well.
a) would require Unity changes (or hierarchical caching), b) and c) could be changed cache-server internal.

*) on my machine, LZ4 compresses at 1000 MB/s, and decompresses at 5000 MB/s, so it'd be a speedup for "put cache" operations up to 4GB LAN, and for "get cache" operations even in the 10GB LAN case, assuming 2x compression.
As an aside, ZSTD compresses even better (3-4x), at >400 MB/s, and decompresses at 1500 MB/s.

**Comment by stephen-palmer** [comment]
Thanks for the input. This is something we can consider for the new cache server for Asset Database V2.
