### ISSUE TITLE
[v6.4] 10.244.95.22:31231 Connection Error: read ECONNRESET  

### ISSUE THREAD

**Issue by z5616342** [Unity-Technologies/unity-cache-server#146]
I have encountered this error
How can I solve it?

**Comment by BrettKercher** [comment]
Did you figure out a fix for this? When were you running into this error? On start up, or while it's already running? Was there a stack trace included in the error message?

I'll follow some of the advice on [this](https://stackoverflow.com/questions/17245881/node-js-econnreset) thread, and add some extra logging when this error occurs.

**Comment by z5616342** [comment]
@BrettKercher thanks，Has the new update solved this problem

**Comment by BrettKercher** [comment]
The update just added a little bit of extra logging to potential help pinpoint the problem. It was likely some sort of network issue causing the problem, which is hard to reproduce/fix. There's a small chance the problem has resolved itself overtime as well, so it may be worth it to try again.
