### ISSUE TITLE
[v6.4]Invalidating transaction with zero (0) value hash for GUID *********************

### ISSUE THREAD

**Issue by z5616342** [Unity-Technologies/unity-cache-server#147]
how to salve this problem?

**Comment by bjlnly** [comment]
I had the same problem.

**Comment by z5616342** [comment]
@bjlnly Have you solved it?

**Comment by bjlnly** [comment]
@stephen-palmer Can you answer this？

**Comment by BrettKercher** [comment]
When the cache server is finalizing the transaction to cache an asset, it checks to make sure that the asset has a valid hash. If it has an invalid hash (in this case, all 0s) it ignores the asset. This can happen for a number of reasons (which someone more familiar with our asset database would have to chime in on), but unless it's happening for a majority of your assets, it should be safe to ignore this message.
