### ISSUE TITLE
Did not get expected reply length (CMD size) from cache server

### ISSUE THREAD

**Issue by kobechenyang** [Unity-Technologies/unity-cache-server#149]
We are getting this error 
`Did not get expected reply length (CMD size) from cache server`
when we trying to run Unity on aws machine through command line on windows, our cache server is currently running on Mac. Also we are using mix versions with same cache server. Is this a network issue or is it a version mismatch? 
From the cache server log it just keeps looping through all the ports. 
```
XXX:1605 connected.
XXX:1606 connected.
XXX:1607 connected.
XXX:1636 connected.
XXX:1638 connected.
XXX:1639 connected.
XXX:1669 connected.
XXX:1670 connected.
XXX:1671 connected.
XXX:1700 connected.
```
Any help is appreciated. Thanks

**Comment by BrettKercher** [comment]
We do technically support mixed versions, but the cache server doesn't namespace/segment based on Unity version as the protocol does not include any version ID in the handshake, so it's not recommended to do so.
It's usually safe to use different versions within a _patch_ release, but not between _minor_ release (so 2019.1.0f3 to 2019.1.0f4 would be relatively safe, but not 2019.1 to 2019.2).

So this is probably some sort of network issue, but we'll have to do some more testing to figure out exactly what's causing the problem, although I've been having trouble reproing the issue myself. Have you been able to make any progress on your end?

**Comment by kobechenyang** [comment]
Hi @BrettKercher  Thanks for your reply. It was something with network settings on aws. We couldn't figure out why. It is working fine when I try running locally. Looks like it is working for a while and then failed. Then it starts trying to connecting to different ports. We also submit a ticket to unity support. https://support.unity3d.com/hc/requests/725486 I have attached logs to that ticket.
