### ISSUE TITLE
unity-cache-server-import fails opaquely when highReliability: true

### ISSUE THREAD

**Issue by thefuntastic** [Unity-Technologies/unity-cache-server#150]
Seeding our 6.3.0 cache server with Json exported from unity. When the server is started with `highReliability: true` running `unity-cache-server-import` shows that it's trying to import 1/xxxxx assets and shows the progress bar but then silently exits. (Also with `multiClient: false`)

The cache server log shows the following (and no other information):
`[Cluster:4] Cannot read property 'toString' of undefined`

When `highReliability: false` import proceed correctly. 

Previously, running the cache server without seeding it, that error message would come up fairly often in day to day usage. While this is only a gut feeling: our server was not warming it's cache as quickly as we expected, even taking into account our `reliabilityThreshold` is set to 2

**Comment by BrettKercher** [comment]
I wasn't able to reproduce this locally. Are you running with the highest log level enabled (4)? And would you be able to send me the .json file you use during the import process? 

I also went ahead and added some extra error handling to the import process to see if that will catch it.
