### ISSUE TITLE
[v6.3.0] Unity throws OOM error when building using cache server

### ISSUE THREAD

**Issue by AccidentallyTheCable** [Unity-Technologies/unity-cache-server#154]
We have multiple projects, and multiple users. Until this one specific project, we had not had any issues with the cache server.

This project, during build, has consistently thrown OOM Errors when the cache server is enabled. Unfortunately I havent been able to figure out what the real cause is, as nothing has pointed to anything specific. Error message from the unity build is below.

We have added memory to both the build server, and the cache server, without resolution. Again, this same setup, and build flags, work fine on numerous other projects, so we're not sure exactly what the issue is here.

When this happens, Build server memory is under 50% of 48GB, and Cache server memory is under 50% of 32GB. This project is pretty large, 116GB unbuilt / in our repository. The issue happens after various files (the line 'Updating....' differs every time, but it always happens in this same area of the process.

[buildfail.end.log](https://github.com/Unity-Technologies/unity-cache-server/files/3826470/buildfail.end.log)

Any other info I can provide, please let me know

**Comment by BrettKercher** [comment]
We made some improvements for large projects in version 6.4. Could you try upgrading to the latest version and seeing if the problem persists? 

#114 is the issue where this has been discussed previously.

**Comment by mleenhardt** [comment]
We have been using 6.4 beta versions for months now (currently on beta 5) and are still running into the issues described in #114. The cache server will regularly starting using 20GB RAM+ although we're only using the disk storage module. Workers regularly get OOM killed, causing various errors, such as `Socket: connect failed, error: A non-blocking socket operation could not be completed immediately` / `Couldn't connect to Cache Server. Unable to connect to host XXX`. This is causing our automated builds to randomly fail and editor users to be prompted with error popups.
