### ISSUE TITLE
 Error: Unrecognized command, aborting! Bad Client protocol version

### ISSUE THREAD

**Issue by tavichh** [Unity-Technologies/unity-cache-server#161]
Hello!
So, I just installed the Unity Cache Server to Ubuntu 19.04 server and I'm having a little bit of an issue with it not allowing connections.

I am running the server via `unity-cache-server` with no arguments but when I connect from Unity (2019.3.0f3 and 2019.3.0b12) it shows the following in the server log.

`
Error: Unrecognized command, aborting!
Bad Client protocol version
`

So, I am thinking it was a port problem so I changed the port from `8126` to `8177` and started it with `unity-cache-server -v 8177` and it still does not work. I have NodeJS LTS installed.

This is the startup log:

```
Cache path is /usr/lib/node_modules/unity-cache-server/.cache_fs
Cache Server version 6.3.0; Cache module is cache_fs
Cache Server ready on port 8126
```

**Comment by BrettKercher** [comment]
Unity versions greater than 2019.3 use our new Asset Database V2, which is incompatible with this version of the cache server. For >2019.3 builds of Unity, try out the [accelerator](https://blogs.unity3d.com/2019/09/11/speed-up-your-team-with-the-unity-accelerator/).

**Comment by BrettKercher** [comment]
I've added some wording about this to the readme for more visibility
