### ISSUE TITLE
Helm chart

### ISSUE THREAD

**Issue by maguro** [Unity-Technologies/unity-cache-server#163]
We have a Helm chart, as well as GCP Terraform files, for setting up a Unity cache server.  The Terraform files setup a VPC w/ appropriate firewall rules that can restrict access to corporate networks.  The Helm chart uses a subchart from [ingress-nginx](https://github.com/kubernetes/ingress-nginx) to setup a Kubernetes `LoadBalancer` for port 8126 which points to a `StatefulSet` based on Docker images from [windyakin](https://github.com/windyakin/docker-unity-cache-server).

Happy to submit if interested.

**Comment by ozgia** [comment]
@maguro  please do
