### ISSUE TITLE
Set custom local cache server

### ISSUE THREAD

**Issue by MartinGonzalez** [Unity-Technologies/unity-cache-server#17]
Hi, is there a way to tell unity that i'm using a custom local cache server with xx size and in xx path via command line/script?

**Comment by stephen-palmer** [comment]
As of Unity 2018.1 there is a `-CacheServerIPAddress [host:port]` command line argument for Unity that will connect to the specified cache server on startup. Size/path options are configured by the server.

**Comment by tfedor** [comment]
@stephen-palmer How are older versions handling connection to CacheServer? Does Unity load settings only on startup or when opening preferences, or each time it is connecting to cache server?

We want to have different Cache Server per different Unity version in case generated files are not compatible between versions. We can change settings via `EditorPrefs` during start up of Unity, but what would happen if we open two different versions of editor at the same time?

Alternatively, is there a way for CacheServer to know what version of Unity is sending files, so we could update CacheServer to use file paths according to Unity version?

**Comment by stephen-palmer** [comment]
Unfortunately Unity stores the cache server configuration in a system wide configuration, and the client/server protocol does not include any version identifier (or I would definitely take advantage of that on the server side). I'm not sure what side effects there would be in modifying EditorPrefs with multiple copies of Unity running - likely, the cache server config read at startup for each of them will be used for the whole session, but I haven't tested this. The command line option added to 2018.1 will forcibly override the stored setting, and will not allow any changes to the global config while it's active.

There is a little bit of hope ... I am in the middle of adding a new server side feature that allows you to set a "reliability threshold" for file uploads. Every time a file is uploaded (identified by GUID and hash - hash being the hash of import inputs), the _byte stream_ hash is computed, and a "reliability factor" is incremented for that file if the _byte stream_ hash matches the previous upload for that file. The cache server will only server files that have a reliability factor >= the configured reliability threshold. So essentially, more than one client must agree on a file's contents before it will server the file.

The main purpose of this feature is to catch non-deterministic asset imports that can end up propagating incorrectly imported assets via the cache server. It also makes caching more reliable in mixed Unity version environments.
