### ISSUE TITLE
How to test if cache server works correctly and if import times are faster?

### ISSUE THREAD

**Issue by roclau0102** [Unity-Technologies/unity-cache-server#171]
I've setup the cache server in our local company network and it seems to work (as in there are no errors), but how do I best confirm that it's actually caching assets and that its beneficial? Are there any tools people use to measure import times with and without the cache server or is the manual test on my local machine the only way to confirm? I've deleted my library and imported the project locally with the cache server enabled and disabled, but it didn't make any meaningful difference. Maybe it's because the project isn't large anyway, but it could also be because it's not actually working.

**Comment by snim2** [comment]
You should have set a cache directory in your config, so you can just watch for files being written to that directory.
