### ISSUE TITLE
Issues connecting to Cache Server through proxy

### ISSUE THREAD

**Issue by ObsessiveNerd** [Unity-Technologies/unity-cache-server#18]
When attempting to connect to the cache server through a proxy, errors matching this a logged:

[Cluster:3] Failed to update mtime of /usr/local/lib/node_modules/unity-cache-server/cache5.0/01/01e02995805eb483690380a911a657e2-3c80496ccf887935b85a3e0fcbe4b6b5.bin: Error: EPERM: operation not permitted, utime '/usr/local/lib/node_modules/unity-cache-server/cache5.0/01/01e02995805eb483690380a911a657e2-3c80496ccf887935b85a3e0fcbe4b6b5.bin'

I have attached the full log as a text file.
[cache-server-logs.txt](https://github.com/Unity-Technologies/unity-cache-server/files/1767699/cache-server-logs.txt)

**Comment by stephen-palmer** [comment]
Is this still occurring for you? Can you elaborate on your cache server configuration? Node version, cache server version, startup CLI options, etc.
