### ISSUE TITLE
Support LaunchAgents or LaunchDaemons on Mac

### ISSUE THREAD

**Issue by yuewah** [Unity-Technologies/unity-cache-server#23]
In UnityCacheServer v5 , I can use LaunchAgents on Mac, However UnityCacheServer v6 is not.

**Comment by stephen-palmer** [comment]
Can you elaborate? What is preventing you from setting up a Launch Agent? To my knowledge we've not provided any specific scripts/code for that in the past.

**Comment by yuewah** [comment]
You are right, there is no official documentation on how to setup previously.
I would like Unity can show more information on how to run unity cache server as Window Servce or LanuchAgent/Daemon on Mac.

**Comment by stephen-palmer** [comment]
I think that's a reasonable request. I did find a user that created some automated scripts around the old cache server ZIP distributions: https://github.com/tnayuki/unitycache-osx-installer

We could add more official support along those lines. I'll leave this open as a feature request.

**Comment by stephen-palmer** [comment]
Closing - see comments in PR #93
