### ISSUE TITLE
Upgrade/operations guide

### ISSUE THREAD

**Issue by msiebuhr** [Unity-Technologies/unity-cache-server#27]
I'm trying to upgrade to the latest version of the cache server, but I'm running into some problems doing so. In particular, v6.0.1 seem quite far from a drop-in replacement

 * `--path` has been renamed to `--cache-path` (and [latest docs](https://docs.unity3d.com/2018.1/Documentation/Manual/CacheServer.html) says `--path`...)
 * Starting without `-w NUM` drops you into a shell of sorts. Seem to confuse our systemd-scripts greatly. Starting with ex. `-w $(grep -c 'model name' /proc/cpuinfo)` starts without a shell.

I feel like I've missed an UPGRADING.md somewhere...

**Comment by stephen-palmer** [comment]
not supporting `--path` is an oversight - that should have been maintained for compatibility.

The "shell" is that it's accepting input, which only functions to listen to a "q" (quit) command .. this can be removed and cleaned up to just intercept ctrl-c and tell the cache to shutdown gracefully. There was some aspiration for more console style commands but that didn't materialize, and I see this is interfering with systemd scripts.

**Comment by stephen-palmer** [comment]
sure - always nice to see how things are being used in Real Life!
