### ISSUE TITLE
--dump-config doesn't dump active config

### ISSUE THREAD

**Issue by msiebuhr** [Unity-Technologies/unity-cache-server#28]
When running with `--dump-config --cache-path XX`, I would expect *Cache.options.cache_fs.cachePath* to be `XX`, but it remains as `.cache_fs`, as if run without any options.

(I tried using it as a shortcut to see what the config would do with different flag configurations...)

**Comment by stephen-palmer** [comment]
This will be fixed with https://github.com/Unity-Technologies/unity-cache-server/pull/65

**Comment by mleenhardt** [comment]
@stephen-palmer I tried specifying the new options in a config file (namely `Cache.options.workers` and `Global.logLevel`) while running the latest on npm (6.1.2) but they weren't applied. Specifying them on the command line still works fine.

**Comment by stephen-palmer** [comment]
The changes are not deployed to a version yet. Sorry for the delay on that.
