### ISSUE TITLE
Suggestion: Tagging

### ISSUE THREAD

**Issue by msiebuhr** [Unity-Technologies/unity-cache-server#31]
We're currently running a cache server per project we're building on our farm + one for use locally by our developers. This is done so we don't have to delete all the cache when a build somewhere turns sour and puts junk in our cache.

Having one for local development (across all games) is because the hooks we have to set the cache server doesn't kick in the moment the developer changes projects, and thus may start using the cache before we've had a chance to set the right server for the project.

While I am unsure if this can be done editor-wise (I maintain our non-Unity code + infrastructure), I propose that the protocol could be extended with per-connection tags/headers (think HTTP headers), which the server then could use to decide what to do with the data. Eg.

 * Use different caches (or different cache-modules) per project/...
 * Break mirroring-loops by including some pedigree about where objects come from.

The protocol could be extended by adding a `ct` for *connection tag*

     client --- 'ct' (size_key <uint64>)(size_value <uint64) + size_key bytes + size_value bytes --> server

(One could also imagine using per-transaction tags, but I don't quite know what they would be used for.)

**Comment by stephen-palmer** [comment]
I like your proposal and have been thinking on this for a while. We're now working through a proposal to add cache namespacing capabilities by packing some more data into the protocol version header. It will be a little simpler to add to the client and backport.

Thanks for the suggestion! closing this for now - will have more info on the namespacing options soon.
