### ISSUE TITLE
Clean Up Script Crashed

### ISSUE THREAD

**Issue by jasongabrielcasale** [Unity-Technologies/unity-cache-server#32]
[Cleanup Script Failure.txt](https://github.com/Unity-Technologies/unity-cache-server/files/1949270/Cleanup.Script.Failure.txt)

**Comment by jasongabrielcasale** [comment]
Here is the failure of our Script. I posted it on Stephens request.

**Comment by stephen-palmer** [comment]
Fixed in release v6.0.2
