### ISSUE TITLE
Design question: Why a custom protocol over ex. HTTP PUT/GET

### ISSUE THREAD

**Issue by msiebuhr** [Unity-Technologies/unity-cache-server#35]
The [Bazel](https://bazel.build) build tool uses [plain HTTP PUT and GET](https://docs.bazel.build/versions/master/remote-caching.html#http-caching-protocol) for caching in circumstances similar to what the Unity Cache Server is built for.

Alternatively: Would it be possible to get HTTP PUT/GET support in Unity, as an alternative to the custom protocol? I.E. giving Unity a base URL and then take it from there?

**Comment by stephen-palmer** [comment]
At the time the cache server was first introduced (a long time ago) it made sense to implement a custom streaming protocol that was simple and efficient. This also, of course, influenced the client side architecture that the Asset Database uses to interface with the Cache Server.  So for Asset Database V1 at least, without significantly refactoring the client (Unity Editor) we are married to this protocol and implementation.

Having said that, I don't think HTTP PUT/GET would be appropriate for this application. We want to saturate the network with as much data as possible from thousands of individual files - GET/PUT has too much overhead. You could arguably build a streamed solution using HTTP/1 chunk encoding, but that protocol is being deprecated in HTTP/2. Stream framing in HTTP/2 might work well.

There is a separate team working on the cache server for ADBV2 - I'm not sure what they are choosing for a protocol so I've asked for clarification.

**Comment by msiebuhr** [comment]
Thanks for the clarification!
