### ISSUE TITLE
Feature Request: Add flag to include timestamps in logs.

### ISSUE THREAD

**Issue by timezombi** [Unity-Technologies/unity-cache-server#39]
When running `unity-cache-server` or `unity-cache-server-cleanup`, all of stdout is shown without any timestamps. Having timestamps prepended to the output could be very useful if you want to collect usage metrics on your Unity Cache Server instance, determine system uptime, or even find out how long the process was running before crashing.

Having something like a `--show-timestamps` runtime argument that prepends the epoch time or a human readable DateTime would be really useful to people that don't want to set up a custom solution for this. An example of what I'm talking about is how `dmesg` handles timestamps (-T, -t, --time-format, and the default behavior which specifies seconds since kernel start).

In the past, I was able to get around issues like this by piping the output to `awk` (e.g. https://stackoverflow.com/questions/21098382/how-to-add-timestamp-while-redirecting-stdout-to-file-in-bash ), but having it done in the script itself would make timestamps less platform dependent without getting into any more complicated logging solutions.

Example of what we are currently using in production... (requires gawk)
`unity-cache-server | awk '{ print strftime("[%Y-%m-%d %H:%M:%S]"), $0; fflush(); }' | tee UnityCacheServer_$(date -d "today" +"%Y%m%d%H%M").log`

The above prepends the timestamp to each line of the log, displays all output to stdout, and saves all output to a log file with the current datetime in the filename. However, doing that requires installing gawk and it looks pretty messy. I could remove the whole awk line if the functionality were added to unity-cache-server.

**Comment by stephen-palmer** [comment]
We could improve the logging situation. I would probably upgrade to something like https://github.com/winstonjs/winston so you could add your own logging transports with custom formats. In the meantime, you are doing it right.  There are simpler tools to use btw, like https://joeyh.name/code/moreutils/

**Comment by stephen-palmer** [comment]
There are no plans at this point to make further improvements here.
