### ISSUE TITLE
Make benchmark suite public

### ISSUE THREAD

**Issue by msiebuhr** [Unity-Technologies/unity-cache-server#46]
In the [v6 announcement blog post](https://blogs.unity3d.com/2018/03/20/cache-server-6-0-release-and-retrospective-optimizing-import/) you talk about a Python load-generator for testing set-ups.

Currently, I've been doing some simple benchmarks (switching platforms on one of our builds) to test tweaks to server-, network- and cache-server-setup, but it is not all that consistent && somewhat annoying to do manually.

So, could you make the benchmark tool public?

(I have toyed with making one myself, hence PR #45)

**Comment by stephen-palmer** [comment]
that python code is very much not release quality, and not what I would consider a good foundation to build on. One thing we will be releasing in the near future is a C# Client Library package for Unity, which could be used to build some actually decent performance suites on top of. It includes a tool that uploads all assets in the current project to a target cache server (superseding the scripts in this repository for doing the same thing)

**Comment by msiebuhr** [comment]
Made a quick-and-dirty load tester using https://github.com/pinterest/bender and a client of my own design:

```sh
go get -u github.com/msiebuhr/ucs/cmd/ucs-bender
ucs-bender # Test against local host
```

It currently does 1/3 "hello" requests, 1/3 all GET's and 1/3 all PUT's (to emulate a fresh build). File-sizes, command-count and such is hard-coded for now, but should be easily configured.
