### ISSUE TITLE
jenkins build android apk failed because  “Couldn't connect to Cache Server.”

### ISSUE THREAD

**Issue by dufenmiao** [Unity-Technologies/unity-cache-server#49]
hi, I build  the game for android platform by jenkins, but build failed because   “Couldn't connect to Cache Server.” While it is ok if the platform is iphone.

**Comment by dufenmiao** [comment]
if I turn on the CacheServer, build for android platform is OK too.

**Comment by stephen-palmer** [comment]
This is a client/editor config issue, not a server issue.
