### ISSUE TITLE
Local Cache Server Fails on Startup, works after entering Preferences

### ISSUE THREAD

**Issue by JashanChittesh** [Unity-Technologies/unity-cache-server#52]
I have also filed this as _(Case 1049486) Local Cache Server Fails on Startup, works after entering Preferences_ via the official bug reporter but haven't received a reply to it so far:

I have sporadically seen the local cacher server fail in previous Unity versions (2017.4.x) but now it's consistent (it happens every time I start Unity, on two different Windows 10 Unity installations):

At first, when I start Unity, I get:

```
Socket: connect failed, error: No connection could be made because the target machine actively refused it.
(0)
UnityEditor.Modules.ModuleManager:RegisterAdditionalUnityExtensions()

connect failed
UnityEditor.Modules.ModuleManager:RegisterAdditionalUnityExtensions()

Couldn't connect to Cache Server.
Unable to connect to host localhost:63993.
UnityEditor.Modules.ModuleManager:RegisterAdditionalUnityExtensions()
```

Then, when I open the preferences, those 3 messages disappear, and it seems the cache server is working because I can check the cache size (but here, I'm assuming that this check is actually going through the interface and not just doing a file-scan). Unfortunately, the local file server UI does not have "Test Connection", which I think should be re-added to make sure this is not ambiguous.

**How we can reproduce it using the example you attached?**

You can follow the steps in this video: https://vimeo.com/275223708

It may or may not be related to the Cache Server location - I have no spaces in the path, which seems to have been a problem in the past. Oh, but I just saw that Unity Hub defaults its installation to "C:\Program Files\Unity\Hub\Editor\2017.4.5f1", so there is a space in there.

This happens for me also with a new empty project; so I don't think adding a project helps. However, it does *not* happen when I create a new project. Only, when I then close that new project and open it again.

**Comment by stephen-palmer** [comment]
Closing in conjunction with https://fogbugz.unity3d.com/f/cases/1049486/ being closed as well.

**Comment by Eyesiah** [comment]
My team and I are also getting this issue frequently. Unfortunately the fogbugz link has no information. Can you give any information about this issue?
