### ISSUE TITLE
[Question] High reliability mod vs standard 

### ISSUE THREAD

**Issue by nppk** [Unity-Technologies/unity-cache-server#58]
Hi everyone!

We are are currently testing unity cache server in our CI setup using the same project in a multi branch setup.

Every-time we run a unity build step in our CI the unity project is cloned to the VM and the seeded unity cache server helps reimport the assets committed earlier reducing the build step time.

Using the cache server has yielded some impressive results in build time reduction , and currently the only issue we are facing is weather to use High Reliability mod or the standard one?

I have a few questions regarding the two:

1. If we use the standard operation mod to commit the assets to unity cache server, what are the  implications of having an unreliable/corrupt binary output caused by the Asset Importer process and then committed to the cache server and later distributed to other clients during build time?
eg: will importing an unreliable .PNG asset using the cache server, create a build error, or everything     will go "smoothly" and the .PNG will be eventually missing when the game is ran? 

2. When using High reliability mod the documentation mentions that once an asset version is checked for binary stability and committed to the cache server it can not be modified,
This statement is a bit confusing
since our assets might sometimes differ between branches and modified, will the modified versions of assets won't be committed to the cache server using high reliability mode? or the cache server will treat them as "new" assets since they have a different GUID and binary hash and still commit them?

Thank you so much!

**Comment by partounian** [comment]
(also curious)

**Comment by stephen-palmer** [comment]
1) The implication of an unstable import is highly dependent on the asset itself. The simple case of a PNG importer is probably not going to result in any tangible problems, outside of possible visual inconsistencies. The worst case we're hoping to catch is importers with post processors that introduce untracked dependencies, which produce unpredictable results based on a project state that may differ between developers. But in any case, this mode of operation is to help you discover inconsistencies in the import process so you have awareness where previously it was very difficult to do so. You could also consider just using High Reliability mode temporarily (periodically) to test a full reimport of your project. After instabilities are identified and corrected (or deemed harmless), disable it again for maximum performance.

2) A version is defined as a GUID+Asset hash combination, so any modification to the asset that affects the hash will be considered a different version.
