### ISSUE TITLE
[Feature Request] Upstream Cache

### ISSUE THREAD

**Issue by awiebe** [Unity-Technologies/unity-cache-server#59]
I don't understand why Unity accepts either a local cache directory **or** a network location.  The usual cache model is to recursively evaluate upstream servers.  

Surely it is most logical to use a hybrid, to evaluate locally, and then check network areas (local **and** network cache).  Even if upstream cache is not implemented in the cache server, at the very least, the client (Unity Editor) should have an option to check locally, and then remotely if there is a cache miss.

**Comment by stephen-palmer** [comment]
The client code is in the middle of a major overhaul as part of the new asset database work, so I don't think there's much stomach for changes on that side. Supporting upstream caches on the server side wouldn't be too difficult to add - perhaps as a "wrapper" cache module. Flagging it as a feature request and leaving this open.

**Comment by awiebe** [comment]
There was a similar problem in the architecture for DNS, what you suggest is similar to recursive DNS.
In **recursive** DNS server will ask an upstream server if it doesn't know about a server name, until the root server is reached.  The problem with this is it **did not scale** to many requests, as the load was all placed on the DNS server.  To combat this the **iterative** model was introduced wherein if a server did not know about a name it would give names of servers that might back to the client, which shifted the lookup burden back on to the client.

I would design it so client first ask for all available cached assets, then cooperate to build new asset caches by racing to generate an uncached asset(pick a random index to reduce collisions).  The servers will keep a timestamp+IPAddr based lock( the server needs to be the lock authority) to prevent multiple clients from trying to generate the same asset.  Then the clients push it back upstream, and the process of downloading cached assets repeats until the AssetDatabase is full.

There are some concurrency issues for ungenerated asset cache, but I imagine the network cache server already handles them.  Here is some pseudocode for the algorithm 

```python
cached_asset_generation():
    server_names=['localhost','s1.local','s2.com']
    for h in asset_hashes:
        for s in server_names:
            r= request(s,r)
            if r.status == '200':
                addToAssetDatabase(h,r.data)
                break
        #Asset not cached
        uncached.add(h)

    #Finished getting all cached, generating uncached
    for h in random.shuffle(uncached):
        lock_success=true
        for s in reversed(server_names):
            #If the server has that resource locked by an earlier client someone else is generating
            status = write_lock_resource(s,h)
            #other status error handling goes here
            lock_success = lock_success and status == 'ok'
            if not lock_success:
                #someone else is in the process of generating this
                uncached.remove(h) #Removed from the uncached list, this will be upstream by the time we poll the servers next
                continue
        if lock_success:
            #we won so we get to generate this resource
            data=generateInternal(h)
            addToAssetDatabase(h,data)
            for s in server_names:
                push_data(s,h,data)
            #Finish pushing before any unlocking happens
            for s in server_names:
                write_unlock_resource(s,h)

main():
    while( not assetDatabase.has_all_data()):
        cached_asset_generation()
```

**Comment by unquietwiki** [comment]
Hey @awiebe @stephen-palmer : what's the appetite for adding something like https://github.com/feross/simple-peer to this, so you can chain together dev stations for caching?

**Comment by stephen-palmer** [comment]
@awiebe thanks for posting this - I think you bring up some good points and suggestions on how to think about cache server scalability in the future. I really like the iterative model.

We're unlikely to continue to extend the current cache server architecture any further, but this will certainly factor in to our thinking for the next major iteration that will accompany the new asset database next year.

**Comment by 986253417** [comment]
how to start up the cache server

**Comment by 986253417** [comment]
how to start up the cache server
