### ISSUE TITLE
Usage of parameter "max-cache-size" of "unity-cache-server-cleanup" is unclear.

### ISSUE THREAD

**Issue by nausicaea** [Unity-Technologies/unity-cache-server#64]
Recently, we've set up a cache server on our network and I would like to regularly schedule cleanups. However, the documentation does not specify what unit to supply to the `max-cache-size` command line parameter of the cleanup script. Does it expect bytes, kilobytes, etc.? Does it accept unit specifications, e.g. `3G` or `3GiB`?

**Comment by nausicaea** [comment]
I did find a reference to the unit in the `README` - `bytes`. It would be nice if the unit was also specified in the command line usage help. :) 

Unfortunately, even if I specify a maximum cache size greater than the currently used space (see below), the cache cleanup script still flags all cached data as expired. Shouldn't I be able to specify an expiration criterion based on size alone?

```
# unity-cache-server-cleanup --cache-path /Library/Caches/com.unity3d.cacheserver --max-cache-size 2000000
Cache path is /Library/Caches/com.unity3d.cacheserver
Found 5319 expired files of 5334. 1.87 GB of 1.87 GB (100%).
Nothing deleted; run with --delete to remove expired files from the cache.
```

**Comment by stephen-palmer** [comment]
The unit (bytes) is printed with the help text, as the option parameter name:

`-s, --max-cache-size <bytes>       Override the configured maximum cache size. Files will be removed from the cache until the max cache size is satisfied, using a Least Recently Used search. A value of 0 disables this check.`

Let me know if for some reason you are seeing different output that this when using the `--help` option.

**Comment by nausicaea** [comment]
I'm sorry, I didn't see that part of the text, must have overlooked it in haste. Thank you anyway and thanks for providing this tool! The cache server has already been very helpful to us.

**Comment by stephen-palmer** [comment]
No problem. Glad you are finding it helpful!
