### ISSUE TITLE
File handles not being released, cleanup fails

### ISSUE THREAD

**Issue by danielresolutiongames** [Unity-Technologies/unity-cache-server#69]
Hey,

Recently (~2-3 weeks ago) switched over to Cache Server version 6.1.2, coming from the older 5.x based implementation before.
Cache module is cache_fs, and using default config by starting the cache server with 
`unity-cache-server -P D:\CacheServer6.0\cache\`
Installed via npm, on a Windows 10 machine (also our build machine).

Once a day I run a Jenkins job like this: 
`unity-cache-server-cleanup -P D:\CacheServer6.0\cache\ --delete`

A few times a week (since we switched) the Jenkins job fails with the following type of error, each time different files:
> D:\CacheServer6.0>unity-cache-server-cleanup -P D:\CacheServer6.0\cache\ --delete 
> Cache path is D:\CacheServer6.0\cache\
> Error: EPERM: operation not permitted, lstat 'D:\CacheServer6.0\cache\ef\ef467a925f5692c468e10b22ddd04901-ee0094957e6a3806dcd58c9fbdcd5b80.bin'
> Build step 'Execute Windows batch command' marked build as failure
> Finished: FAILURE

If I then manually run the cleanup process the same thing happens; I don't *think* Jenkins is the culprit here.

When inspecting node.exe via ProcessExplorer, I find the aforementioned file in an open file handle and never "letting go".
![cacheserver_filehandle](https://user-images.githubusercontent.com/26087495/48563731-3e05d000-e8f5-11e8-99b7-fff88af2a265.PNG)

However, if I restart the running cache server the file handle is released/probably never picked up again, and the cleanup script runs successfully.

Apart from this, the cacheserver window gives sensible output and no warnings, for example:

> Sent 20908 of 20908 requested files (99972 chunks) totaling 4.83 GB in 40.576 seconds (121.83 MB/sec)

I could tell Jenkins to restart the cache server once per night before running the cleaner, but it feels like an issue that would be better solving "properly", and I'm wondering if it is an configuration error from my end or "a bug".

The cache-size is currently at ~60gb.

**Comment by danielresolutiongames** [comment]
I have now upped the loglevel to 5, to see if I figure out any information on why or how this occurs.

**Comment by stephen-palmer** [comment]
It looks like the cache server has that file open (either it's a file being written to or read) and the cleanup script is trying to to read it's meta data (using lstat) and failing .. as part of walking the cache directory to find cache eviction candidates.

I think we just need to wrap that call in a try/catch block, ignoring files that are already open.

**Comment by danielresolutiongames** [comment]
I agree, the file handle is open, but it stays open regardless of any activity to the cache server. I would guess the file is not actively being read or written to; it probably was but something broke halfway through and it was never released. The handle stays open, for example over the weekend, until I restart.

**Comment by danielresolutiongames** [comment]
Generally just one file (handle). I don't know how many more there would be if I let it be for a while. There's yet another one just now, and I haven't restarted yet so if there's anything you want me to deep dive debug into let me know.

I did a `netstat -a -n -o` and the pid for node.js (10724 here) has "just one" port open always:
```
...
  TCP    0.0.0.0:7680           0.0.0.0:0              LISTENING       1840
  TCP    0.0.0.0:8126           0.0.0.0:0              LISTENING       10724
  TCP    0.0.0.0:34999          0.0.0.0:0              LISTENING       2180
...
```
Of course, it opens and closes connections as it gets accessed by users and/or the Jenkins agent (running on the same machine).

**Comment by danielresolutiongames** [comment]
> Generally just one file (handle).

Until I restart the Cache Server of course, since I want Jenkins to be a happy camper. I could leave it for a day or two if that would be relevant?

**Comment by stephen-palmer** [comment]
It would be nice to know if there is a chronic problem of open file handles piling up. They should be cleaned up when the socket is closed and all related file handles go out of scope.

**Comment by danielresolutiongames** [comment]
Ok, I'll leave it for a bit.

Unfortunately I'm not piping the logfile to a file, so loglevel 5 with these types of messages 
```
127.0.0.1:59423 connected.
127.0.0.1:59423 closed connection.
```
from cmd won't really say anything interesting after 30 minutes or so. I won't be able to tell if there for example was a connection that was never closed according to unity-cache-server (but of course closed according to Windows), which would have been interesting. :(

Maybe hinting at a feature request to log to file?

**Comment by stephen-palmer** [comment]
At least in the currently unsophisticated implementation of logging, I believe pretty strongly that logging redirection should be an exercise left to the operating system. If we did anything further with logging, I would integrate Winston or some other configurable log transport module.

**Comment by danielresolutiongames** [comment]
At the end of the day I'm now up to 4 file handles constantly open. Today I had at least one build/library import aborted midway, so it might have been that a connection between that Editor and the server was forcefully killed, non-gracefully. If the Editor didn't have time to send a "goodbye", would that generate issues like these, do you think?

**Comment by stephen-palmer** [comment]
We'll have to do some debugging to see if that's the case. It doesn't _seem_ like it should matter but obviously something is going on that's preventing the files from being closed.
