### ISSUE TITLE
Configuration Cache.options.processor is required

### ISSUE THREAD

**Issue by xer0x** [Unity-Technologies/unity-cache-server#70]
Hi, thanks for unity-cache-server. 

We've recently upgraded from 6.0.x to 6.1.2, and were surprised that the server wouldn't start because of a missing configuration key. We use a custom configuration file that was sufficient for 6.0.x.

Our error:
```
Error: Configuration property "Cache.options.processor" is not defined
```

We added `Cache.options.processor.putWhitelist` to our configuration file and everything is working fine. Perhaps a better workaround for us would be to stop using a configuration file, and switch to using command line flags.

I'm creating a bug because this was a surprise, and if the config key has a valid default value, then we shouldn't be required to explicitly put it into our configuration.

**Comment by stephen-palmer** [comment]
Thanks for the report. You're right, this shouldn't cause an error. I'll have a fix in the next release.
