### ISSUE TITLE
Cannot run `npm start` from local folder after recent update

### ISSUE THREAD

**Issue by rasmus-unity** [Unity-Technologies/unity-cache-server#71]
Previously it was possible to run cache server locally from repo/code simply by running `npm start`, no need to install anything globally etc.

When trying now, getting
```
$ npm start

> unity-cache-server@6.1.2 start /Users/.../unity-cache-server
> node main.js

module.js:557
    throw err;
    ^

Error: Cannot find module '../package.json'
```

Would it be possible to again be able to run cache server locally, without having to install globally? (which seems according to readme, to be the "official" way of running now)

Thanks,
Rasmus

**Comment by stephen-palmer** [comment]
Just tested locally and I believe this will be fixed in the next release, which includes a big refactor of CLI handling code. You can verify by cloning `master`.
