### ISSUE TITLE
Version 6.2.3 performance [Feedback requested]

### ISSUE THREAD

**Issue by stephen-palmer** [Unity-Technologies/unity-cache-server#91]
I did some quick performance profiling of v6.1.2 vs. v6.2.3. Here are the results of back-to-back imports of the same project, from a server running on the same local system (using Assets -> Reimport All in the Editor). This is on a Macbook Pro 2017 with SSD.

Cache Server version 6.2.3; Cache module is cache_fs
Cache Server ready on port 8126
Sent 1570 of 1570 requested files (16563 chunks) totaling 963.6 MB in 5.099 seconds (188.98 MB/sec)
Sent 1570 of 1570 requested files (16563 chunks) totaling 963.6 MB in 4.283 seconds (224.98 MB/sec)
Sent 1570 of 1570 requested files (16563 chunks) totaling 963.6 MB in 3.508 seconds (274.69 MB/sec)
Sent 1570 of 1570 requested files (16563 chunks) totaling 963.6 MB in 3.457 seconds (278.74 MB/sec)

Cache Server version 6.1.2; Cache module is cache_fs
Cache Server ready on port 8126
Sent 1570 of 1570 requested files (16563 chunks) totaling 963.6 MB in 3.92 seconds (245.82 MB/sec)
Sent 1570 of 1570 requested files (16563 chunks) totaling 963.6 MB in 3.894 seconds (247.46 MB/sec)
Sent 1570 of 1570 requested files (16563 chunks) totaling 963.6 MB in 4.05 seconds (237.93 MB/sec)

Cache Server version 6.2.3; Cache module is cache_fs
Cache Server ready on port 8126
Sent 1570 of 1570 requested files (16563 chunks) totaling 963.6 MB in 3.69 seconds (261.14 MB/sec)
Sent 1570 of 1570 requested files (16563 chunks) totaling 963.6 MB in 3.651 seconds (263.93 MB/sec)
Sent 1570 of 1570 requested files (16563 chunks) totaling 963.6 MB in 3.377 seconds (285.34 MB/sec)

So between the 2nd and 3rd run, there's about a 10% performance increase on average. Can anyone else confirm some perf improvements in the new version? Would love to see some numbers on LAN  environments as well.

**Comment by timezombi** [comment]
You've been very good about quickly fixing bugs / scaling issues for us on our ridiculously sized Cache Server Instance, so I would love to be of help.

The whole office is going to be on vacation soon. After Christmas, I can bring down our production servers to run some tests for a couple days.

1) In our environment, our build server accesses UCS through 20gbps links. I'll bring down a Jenkins node to test this case.
2) Our workstations are all connected through single 1gbps links. I'll use my workstation for this one.
3) Finally, I'll try building a separate VM on the same host as UCS.

Do you have a preferred log level you want set for this? Any other special things you want setup?

**Comment by stephen-palmer** [comment]
Thanks Brandon!

I just used the default log level (3) to get the summary logs after each connection was closed. Then using Unity as the client to reimport all over and over again.

This did make me think about how to implement some simple profiling helpers, and today I worked on serializing out the incoming data stream from clients, so they could be quickly "played back" against the server. That way you can skip all of the other overhead incurred during an import in Unity (hash calculation, script compilation, importing of non-cacheable assets, etc.)

**Comment by stephen-palmer** [comment]
closing - will reopen when the diagnostic tools are in a release.

**Comment by timezombi** [comment]
Sorry, I lost track of this leading up to the announcement of our game. The opportunity to test it never materialized over the break, unfortunately. I may have a new opportunity to do some tests all through this week up until Memorial Day weekend, however.

Is there something like the `feature/diagnostic-tools branch` that I can try to use for testing 6.4.0b2? I'm starting stress testing of our test cache server instance with our build infrastructure. 

Without the diagnostic tools, I plan on taking the primitive approach of deleting Library/Temp directories on each of our nodes and then attempting to make builds.

**Comment by stephen-palmer** [comment]
I was actually thinking earlier this week about how to get this into a release. What I'll probably do is get the basic stream recording capability into this repo, then move the `stream_player` script to a personal repo.

In the meantime, if you are willing to use a repo clone directly, I pushed `feature/diagnostics-tools` with latest master merged. This would be the equivalent of v6.4.0b2 with the diagnostic tools.
