### ISSUE TITLE
Manager process never restarts dead worker processes

### ISSUE THREAD

**Issue by SGDavid** [Unity-Technologies/unity-cache-server#94]
Worker processes silently die over time and are never restarted by the manager process. This undermines the performance of the cache server until it is restarted, which has to be timed not to interfere with active connections to instances of the Unity Editor. Requesting an enhancement so that the manager process forks new worker processes as necessary.

**Comment by stephen-palmer** [comment]
Thanks for the report!

**Comment by stephen-palmer** [comment]
I published this change to 6.2.4-beta1 if you want to give it a try. It's the only change from v6.2.3. `npm install unity-cache-server@beta`

**Comment by SGDavid** [comment]
Thanks for the quick fix! However, I am running the server (and npm) on a system and userid other than my own, and getting the error below, even though I have set up my private key in ssh-agent. Can you verify the package name passed to npm? Thanks!
`/usr/bin/git ls-remote -h -t ssh://git@github.com/Unity-Technologies/unity-cache-server%40beta.git`
`Unity-Technologies/unity-cache-server@beta is not a valid repository name`

**Comment by SGDavid** [comment]
Works great, with one caveat. If you kill a process with INT or TERM, the handler at line 166 takes over.

**Comment by stephen-palmer** [comment]
Yes, that's necessary for handling (and testing) CTRL-C graceful shutdown. The KILL signal can be used to force recycle a worker. Anyhow I think the primary use case (to address your original issue) is to catch non-signaled terminations and crashes.

**Comment by stephen-palmer** [comment]
Fixed in v6.2.4 (published to NPM)
